apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: hr
  newName: chatbotconatiner.azurecr.io/hr
  newTag: "#{Build.BuildNumber}#"
- name: fiber
  newName: chatbotconatiner.azurecr.io/fiber
  newTag: "#{Build.BuildNumber}#"
- name: motor
  newName: chatbotconatiner.azurecr.io/motor
  newTag: "#{Build.BuildNumber}#"
- name: claim
  newName: chatbotconatiner.azurecr.io/claim
  newTag: "#{Build.BuildNumber}#"
- name: frontend
  newName: chatbotconatiner.azurecr.io/frontend
  newTag: "#{Build.BuildNumber}#"
resources:
- secret.yaml
- sync.yaml
- hr.yaml
- fiber.yaml
- motor.yaml
- claim.yaml
- frontend.yaml
- ingress.yaml
