---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: chatbot-secrets-provider
spec:
  provider: azure
  secretObjects:
  - data:
    - key: azure-openai-endpoint.txt
      objectName: azure-openai-endpoint
    secretName: azure-openai-endpoint
    type: Opaque
  - data:
    - key: azure-openai-api-key.txt
      objectName: azure-openai-api-key
    secretName: azure-openai-api-key
    type: Opaque
  - data:
    - key: azure-deployment-name.txt
      objectName: azure-deployment-name
    secretName: azure-deployment-name
    type: Opaque
  - data:
    - key: azure-api-version.txt
      objectName: azure-api-version
    secretName: azure-api-version
    type: Opaque
  - data:
    - key: cosmos-db-endpoint.txt
      objectName: cosmos-db-endpoint
    secretName: cosmos-db-endpoint
    type: Opaque
  - data:
    - key: cosmos-db-key.txt
      objectName: cosmos-db-key
    secretName: cosmos-db-key
    type: Opaque
  - data:
    - key: cosmos-db-database-id.txt
      objectName: cosmos-db-database-id
    secretName: cosmos-db-database-id
    type: Opaque
  - data:
    - key: cosmos-db-container-id.txt
      objectName: cosmos-db-container-id
    secretName: cosmos-db-container-id
    type: Opaque
  - data:
    - key: fiber-cosmos-db-container-id.txt
      objectName: fiber-cosmos-db-container-id
    secretName: fiber-cosmos-db-container-id
    type: Opaque
  - data:
    - key: azure-fileshare-conn-str.txt
      objectName: azure-fileshare-conn-str
    secretName: azure-fileshare-conn-str
    type: Opaque
  - data:
    - key: azure-file-share-name.txt
      objectName: azure-file-share-name
    secretName: azure-file-share-name
    type: Opaque
  - data:
    - key: backend-domain-hr.txt
      objectName: backend-domain-hr
    secretName: backend-domain-hr
    type: Opaque
  - data:
    - key: backend-domain-motor.txt
      objectName: backend-domain-motor
    secretName: backend-domain-motor
    type: Opaque
  - data:
    - key: backend-domain-fiber.txt
      objectName: backend-domain-fiber
    secretName: backend-domain-fiber
    type: Opaque
  - data:
    - key: backend-domain-claim.txt
      objectName: backend-domain-claim
    secretName: backend-domain-claim
    type: Opaque
  - data:
    - key: azure-openai-embedding-model.txt
      objectName: azure-openai-embedding-model
    secretName: azure-openai-embedding-model
    type: Opaque
  - data:
    - key: azure-embedding-openai-endpoint.txt
      objectName: azure-embedding-openai-endpoint
    secretName: azure-embedding-openai-endpoint
    type: Opaque
  - data:
    - key: azure-embedding-openai-api-key.txt
      objectName: azure-embedding-openai-api-key
    secretName: azure-embedding-openai-api-key
    type: Opaque
  - data:
    - key: azure-sql-server.txt
      objectName: azure-sql-server
    secretName: azure-sql-server
    type: Opaque
  - data:
    - key: azure-sql-database.txt
      objectName: azure-sql-database
    secretName: azure-sql-database
    type: Opaque
  - data:
    - key: azure-sql-user.txt
      objectName: azure-sql-user
    secretName: azure-sql-user
    type: Opaque
  - data:
    - key: azure-sql-password.txt
      objectName: azure-sql-password
    secretName: azure-sql-password
    type: Opaque
  - data:
    - key: azure-search-endpoint.txt
      objectName: azure-search-endpoint
    secretName: azure-search-endpoint
    type: Opaque
  - data:
    - key: azure-search-key.txt
      objectName: azure-search-key
    secretName: azure-search-key
    type: Opaque
  - data:
    - key: neo4j-uri.txt
      objectName: neo4j-uri
    secretName: neo4j-uri
    type: Opaque
  - data:
    - key: neo4j-user.txt
      objectName: neo4j-user
    secretName: neo4j-user
    type: Opaque
  - data:
    - key: neo4j-pass.txt
      objectName: neo4j-pass
    secretName: neo4j-pass
    type: Opaque
  - data:
    - key: tls.key
      objectName: altudo-net
    - key: tls.crt
      objectName: altudo-net
    secretName: chatbot-tls
    type: kubernetes.io/tls
  parameters:
    keyvaultName: chat-bot-secret
    objects: |
      array:
        - |
          objectName: azure-openai-endpoint
          objectType: secret
        - |
          objectName: azure-openai-api-key
          objectType: secret
        - |
          objectName: azure-deployment-name
          objectType: secret
        - |
          objectName: azure-api-version
          objectType: secret
        - |
          objectName: cosmos-db-endpoint
          objectType: secret
        - |
          objectName: cosmos-db-key
          objectType: secret
        - |
          objectName: cosmos-db-database-id
          objectType: secret
        - |
          objectName: cosmos-db-container-id
          objectType: secret
        - |
          objectName: fiber-cosmos-db-container-id
          objectType: secret
        - |
          objectName: azure-fileshare-conn-str
          objectType: secret
        - |
          objectName: azure-file-share-name
          objectType: secret
        - |
          objectName: backend-domain-hr
          objectType: secret
        - |
          objectName: backend-domain-motor
          objectType: secret
        - |
          objectName: backend-domain-fiber
          objectType: secret
        - |
          objectName: backend-domain-claim
          objectType: secret
        - |
          objectName: azure-openai-embedding-model
          objectType: secret
        - |
          objectName: azure-embedding-openai-endpoint
          objectType: secret
        - |
          objectName: azure-embedding-openai-api-key
          objectType: secret
        - |
          objectName: azure-sql-server
          objectType: secret
        - |
          objectName: azure-sql-database
          objectType: secret
        - |
          objectName: azure-sql-user
          objectType: secret
        - |
          objectName: azure-sql-password
          objectType: secret
        - |
          objectName: azure-search-endpoint
          objectType: secret
        - |
          objectName: azure-search-key
          objectType: secret
        - |
          objectName: neo4j-uri
          objectType: secret
        - |
          objectName: neo4j-user
          objectType: secret
        - |
          objectName: neo4j-pass
          objectType: secret
        - |
          objectName: altudo-net
          objectType: secret
    useVMManagedIdentity: "true"
    userAssignedIdentityID: b42c48c0-6f09-41c5-bfa1-ee9da18a389d
    tenantId: 285f0774-2f69-4657-9b51-6c34e0337532